spring.application.name=backendFotograf
spring.datasource.url=jdbc:postgresql://localhost:5432/masa_portfolio
spring.datasource.username=mihajlodjordjevic
# Ako te ne pusti bez ?ifre, ovde stavi username tvog Mac-a (npr. mihajlo) ili ostavi prazan password
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


app.jwt.secret=${JWT_SECRET:9a7534b82d92c23592658a2d04a6212b1a8d436a72e8162f4319b932c023d8c1}

# Cloudflare R2 Konfiguracija
cloudflare.r2.endpoint=https://cfa4ffbf5eb55f4ad8ca61624b1951e5.r2.cloudflarestorage.com
cloudflare.r2.bucket-name=masa-portfolio-slike
cloudflare.r2.public-url=https://pub-4097dab556f841429caffe6d0c555a62.r2.dev

# Bezbedno povla?enje klju?eva iz sistema
cloudflare.r2.access-key=${R2_ACCESS_KEY}
cloudflare.r2.secret-key=${R2_SECRET_KEY}

# Maksimalna veli?ina pojedina?nog fajla
spring.servlet.multipart.max-file-size=50MB
# Maksimalna ukupna veli?ina celog zahteva (sve slike zajedno)
spring.servlet.multipart.max-request-size=100MB