spring.application.name=backendFotograf
spring.datasource.url=jdbc:postgresql://localhost:5432/masa_portfolio
spring.datasource.username=mihajlodjordjevic
# Ako te ne pusti bez ?ifre, ovde stavi username tvog Mac-a (npr. mihajlo) ili ostavi prazan password
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


app.jwt.secret=${JWT_SECRET:9a7534b82d92c23592658a2d04a6212b1a8d436a72e8162f4319b932c023d8c1}